### ISSUE TITLE
For-else section refers to serialization

### ISSUE THREAD

**Issue by nathanjmcdougall** [when-of-python/web#2]
This part doesn't make sense to me:

https://github.com/when-of-python/web/blob/a180cbb01e3ee026d2676fd566bc2620b5e36401/catalogue/catalogue/for-else.md?plain=1#LL12C1-L12C38

Maybe this was accidentally pulled through from the pickle section.

**Comment by ben-denham** [comment]
Thanks for spotting that, finally fixed by: https://github.com/when-of-python/web/commit/829f9d768d8f51a086a6ceb0b243dc6c1e9c7f9a
